---
- name: store facts
  set_fact:
    APP_URL: "{{ puma_app_url }}"
  tags:
  - facts

- name: Config puma.rb
  template:
    dest: "{{ puma_config_file }}"
    src: "puma.rb.j2"
  become: yes
  become_user: "{{ puma_user }}"

- include_tasks: "{{ puma_service_type }}.yml"
