---
# TODO: check before debconf-show ttf-mscorefonts-installer | grep 'msttcorefonts/accepted-mscorefonts-eula: true'
- shell: 'echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections'
  name: 'Accept MScorefonts EULA'

- name: Install imagemagick and libmagickwand for rmagick
  apt:
    pkg: "{{ query('flattened', ['{{ imagemagick_packages }}', '{{ image_optimization_packages }}']) }}"
