---
- name: Apt | Add key for passenger repos
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x561F9B9CAC40B2F7 id=AC40B2F7 state=present

- name: Apt | Add support for https
  when: 'nginx_install_from_passenger_repo'
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    pkg:
    - "apt-transport-https"
    - "ca-certificates"

- name: Apt | Add passenger repo
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_lsb.codename }} main' state=present update_cache=yes

- import_tasks: 'trusty.yml'
  when: ansible_distribution_version is version('17.04', '<')

- import_tasks: 'bionic.yml'
  when: ansible_distribution_version is version('17.04', '>=')

- name: Service | Ensure nginx is running
  service: name=nginx state=started enabled=yes

- include_tasks: "config.yml"
