---
- name: Apt | Add key for passenger repos
  when: 'nginx_install_from_passenger_repo'
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x561F9B9CAC40B2F7 id=AC40B2F7 state=present

- name: Apt | Add support for https
  when: 'nginx_install_from_passenger_repo'
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    pkg:
    - "apt-transport-https"
    - "ca-certificates"

- name: Apt | Add passenger repo
  when: 'nginx_install_from_passenger_repo'
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_lsb.codename }} main' state=present update_cache=yes

- name: Pkg | Install nginx passenger packages
  apt:
    state: present
    pkg: "{{nginx_install_packages}}"
  notify: nginx restart

- shell: nginx -V 2>&1 | grep ngx_brotli
  register: nginx_brotli_compiled
  ignore_errors: True
  changed_when: No
  name: "Check, if nginx has already compiled Brotli support"

- include: 'brotli.yml'
  when: nginx_brotli_compiled.rc != 0

- name: Service | Ensure nginx is running
  service: name=nginx state=started enabled=yes

- include: "config.yml"
