# based on https://www.phusionpassenger.com/library/install/nginx/install/oss/trusty/
- name: Pkg | Install nginx passenger packages
  apt:
    pkg:
      - "libnginx-mod-http-passenger"
      - "nginx-extras"
      - "passenger"
  notify: nginx restart

# this file will be created by passenger updates
- copy:
    dest: /etc/nginx/conf.d/mod-http-passenger.conf
    content: |
      ### Begin automatically installed Phusion Passenger config snippet ###
      passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
      passenger_ruby /usr/bin/passenger_free_ruby;
      ### End automatically installed Phusion Passenger config snippet ###
  name: "Create default passenger module config"

