#
# enables upstart user jobs
#
- include_tasks: precise.yml
  when: (ansible_distribution == 'Ubuntu') and (ansible_lsb.major_release|int <= 13)

- name: Create ~/.init folder
  file:
    path: ~/.init
    state: directory
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ users }}"
  when: ansible_os_family == "Debian"

- include_tasks: trusty.yml
  when: (ansible_distribution == 'Ubuntu') and (ansible_lsb.major_release|int >= 14)
