- name: Tell sidekiq to not accept new work
  shell: 'pgrep -u -f "sidekiq" | xargs kill -USR1 | exit 0'

  service:
    name: "{{sidekiq_job_name}}"
    state: reloaded
  ignore_errors: true
    sidekiq: reload

- command: '/bin/true'
  name: 'Make sure sidekiq is started at the end'
  notify: restart sidekiq (systemd)

