- name: Tell sidekiq to not accept new work
  shell: 'sudo -n /bin/systemctl kill -s USR1 {{sidekiq_job_name}}'
  ignore_errors: true

- command: '/bin/true'
  name: 'Make sure sidekiq is started at the end'
  notify: restart sidekiq (systemd)

