- name: restart sidekiq (upstart)
  shell: "{{ profile }}'restart {{ sidekiq_job_name }} || start {{ sidekiq_job_name }}'"

- name: restart sidekiq (systemd)
  service:
    name: "{{sidekiq_job_name}}"
    state: restarted
