- name: install dependencies
  apt:
    update_cache: true
    cache_valid_time: 3600
    pkg: "{{ nodejs_dependencies }}"

- name: install additional
  apt:
    pkg: "{{ nodejs_install }}"

- name: add repository and install its signing key
  shell: curl -sL https://deb.nodesource.com/setup_{{ nodejs_version_map[nodejs_version] }} | bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: install nodejs
  apt:
    pkg: "{{ 'nodejs' if 'nodejs' in nodejs_version else 'iojs' }}"
    update_cache: true
    state: latest
