- name: Create {{good_job_job_name}}.service for systemd
  template:
    src: good_job.service.j2
    dest: /lib/systemd/system/{{good_job_job_name}}.service
  register: good_jobtpl


- systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: "{{good_job_job_name}}"
  when: good_jobtpl.changed
  ignore_errors: true
  name: "Enable/Reload systemd"

- template:
    src: 'sudoers.j2'
    dest: '/etc/sudoers.d/{{good_job_job_name}}'
  name: "Enable passwordless sudo for job control of {{good_job_job_name}}"
