#
# perform a bundle run
#
---
- include_vars: RedHat.yml
  when: ansible_os_family == "RedHat"
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Bundle install
  command: >
    {{ profile }}
    'bundle install
    {% if bundle_deployment %}
    --deployment
    {% endif %}
    {% if bundle_generate_binstubs %}--binstubs {{ bundle_binstubs }}
    {% else %}--no-binstubs {% endif %}
    {% if bundle_frozen %} --frozen {% endif %}
    --jobs {{bundle_jobs}}
    --gemfile {{ bundle_gemfile }}
    --path {{ bundle_path }}
    --without {{ bundle_without | join(' ') }}
    {{ bundle_flags | join(' ') }}'
  args:
    chdir: "{{ RAILS_APP_RELEASE_PATH }}"
  register: rails_bundle_result
  changed_when: >
    rails_bundle_result.stdout is defined
    and 'Installing' in rails_bundle_result.stdout
  notify:
  - restart rails app
