- name: sidekiq config
  template:
    src: "sidekiq.yml.j2"
    dest: "{{ sidekiq_config_file }}"
  become: yes
  become_user: "{{ sidekiq_upstart_user }}"

- include_tasks: "upstart.yml"
  when: ansible_service_mgr != "systemd"
- include_tasks: "systemd.yml"
  when: ansible_service_mgr == "systemd"
